### ISSUE TITLE
1

### ISSUE THREAD

**Issue by DenisTymchuk** [Shrralis/ss-elevator-system#1]
You can replace this code:
`person.getCurrFloor() > elevator.getCurrFloor() ?
                            person.getCurrFloor() - elevator.getDestFloor() :
                            elevator.getDestFloor() - person.getCurrFloor()`
to
`Math.abs(person.getCurrFloor() - elevator.getDestrFloor())`

**Comment by shrralis** [comment]
Cool, I'll do that.
