### ISSUE TITLE
2

### ISSUE THREAD

**Issue by DenisTymchuk** [Shrralis/ss-elevator-system#2]
If you use Math.abs() you can replace these 2 blocks with one
`else {
                result = (elevator.getDestFloor() - elevator.getCurrFloor()) +
                        (elevator.getDestFloor() - person.getCurrFloor()) +
                        (person.getDestFloor() - person.getCurrFloor());
            }
        } else if (elevator.getState().equals(Elevator.State.DOWN)) {
            result = (elevator.getCurrFloor() - elevator.getDestFloor()) +
                    (person.getDestFloor() - person.getCurrFloor()) +
                    (person.getCurrFloor() > elevator.getCurrFloor() ?
                            person.getCurrFloor() - elevator.getDestFloor() :
                            elevator.getDestFloor() - person.getCurrFloor());
        `

**Comment by DenisTymchuk** [comment]
class Main, line 59 - 70

**Comment by shrralis** [comment]
Thx, I've needed something like that.
